name: compliance-scan

on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Launching a compliance Scan of all Azure Policies contained in this Repo'
  # schedule:    
  #   - cron:  '0 8 * * *'  # runs every morning 8am
jobs:
  assess-policy-compliance:    
    runs-on: ubuntu-latest
    steps:         
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_ce96fa1c}}
        allow-no-subscriptions: true

    - name: Check for resource compliance
      uses: azure/policy-compliance-scan@v0
      with:
        scopes: |
          /subscriptions/6094e15e-3e04-47b5-9b3b-aa8ae3cf1e52/resourceGroups/jdld-we-demo-wvd-rg1